### ISSUE TITLE
crashed , can not run

### ISSUE THREAD

**Issue by liaolunhui** [rajubd49/PDFKit_Sample#2]
2019-10-06 22:00:13.490647+0800 PDFKit_Sample[3135:74870] libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
CoreGraphics PDF has logged an error. Set environment variabe "CG_PDF_VERBOSE" to learn more.
2019-10-06 22:00:13.664229+0800 PDFKit_Sample[3135:74870] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b7826fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010ad26ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b782555 +[NSException raise:format:] + 197
	3   QuartzCore                          0x000000010ee732ae _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 140
	4   QuartzCore                          0x000000010ee6268b -[CALayer setPosition:] + 57
	5   QuartzCore                          0x000000010ee62de3 -[CALayer setFrame:] + 560
	6   PDFKit                              0x000000010bbdb097 -[PDFPageLayerTile initWithFrame:forPageLayer:withRenderingTransform:tileContentsScale:generationID:] + 168
	7   PDFKit                              0x000000010bbe0805 -[PDFPageLayer _updateTiles] + 3439
	8   PDFKit                              0x000000010bbdbd8e -[PDFPageLayer setNeedsTilesUpdate] + 87
	9   PDFKit                              0x000000010bbf097d -[PDFPageView setNeedsTilesUpdate] + 48
	10  PDFKit                              0x000000010bbf2816 -[PDFPageView setFrame:] + 334
	11  PDFKit                              0x000000010bbe911c -[PDFDocumentView createPageViewForPageAtIndex:] + 764
	12  PDFKit                              0x000000010bbea326 -[PDFDocumentView updateVisibility] + 1726
	13  PDFKit                              0x000000010bc5976f -[PDFView resizeDisplayView:] + 517
	14  PDFKit                              0x000000010bc52cdf -[PDFView layoutDocumentView] + 464
	15  PDFKit                              0x000000010bc4e36a -[PDFView setDocument:waitDuration:] + 1246
	16  PDFKit_Sample                       0x000000010a4373aa -[PDFReaderViewController preparePDFViewWithPageMode:] + 1626
	17  PDFKit_Sample                       0x000000010a436581 -[PDFReaderViewController viewDidLoad] + 1057
	18  UIKitCore                           0x000000011214643b -[UIViewController loadViewIfRequired] + 1183
	19  UIKitCore                           0x0000000112146868 -[UIViewController view] + 27
	20  UIKitCore                           0x000000011277ec33 -[UIWindow addRootViewControllerViewIfPossible] + 122
	21  UIKitCore                           0x000000011277f327 -[UIWindow _setHidden:forced:] + 289
	22  UIKitCore                           0x0000000112791f86 -[UIWindow makeKeyAndVisible] + 42
	23  UIKitCore                           0x0000000112741f1c -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4555
	24  UIKitCore                           0x00000001127470c6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1617
	25  UIKitCore                           0x0000000111f8c6d6 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 904
	26  UIKitCore                           0x0000000111f94fce +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	27  UIKitCore                           0x0000000111f8c2ec -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
	28  UIKitCore                           0x0000000111f8cc48 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1091
	29  UIKitCore                           0x0000000111f8afba __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 782
	30  UIKitCore                           0x0000000111f8ac71 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	31  UIKitCore                           0x0000000111f8f9b6 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 576
	32  UIKitCore                           0x0000000111f90610 _performActionsWithDelayForTransitionContext + 100
	33  UIKitCore                           0x0000000111f8f71d -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	34  UIKitCore                           0x0000000111f946d0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	35  UIKitCore                           0x00000001127459a8 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 514
	36  UIKitCore                           0x00000001122fcdfa -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	37  FrontBoardServices                  0x000000011713e125 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	38  FrontBoardServices                  0x0000000117147ed6 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 283
	39  FrontBoardServices                  0x0000000117147700 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	40  libdispatch.dylib                   0x000000010d163db5 _dispatch_client_callout + 8
	41  libdispatch.dylib                   0x000000010d1672ba _dispatch_block_invoke_direct + 300
	42  FrontBoardServices                  0x0000000117179146 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	43  FrontBoardServices                  0x0000000117178dfe -[FBSSerialQueue _performNext] + 451
	44  FrontBoardServices                  0x0000000117179393 -[FBSSerialQueue _performNextFromRunLoopSource] + 42
	45  CoreFoundation                      0x000000010b6e9be1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	46  CoreFoundation                      0x000000010b6e9463 __CFRunLoopDoSources0 + 243
	47  CoreFoundation                      0x000000010b6e3b1f __CFRunLoopRun + 1231
	48  CoreFoundation                      0x000000010b6e3302 CFRunLoopRunSpecific + 626
	49  GraphicsServices                    0x00000001119d92fe GSEventRunModal + 65
	50  UIKitCore                           0x0000000112748ba2 UIApplicationMain + 140
	51  PDFKit_Sample                       0x000000010a439e00 main + 112
	52  libdyld.dylib                       0x000000010d1d8541 start + 1
	53  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by rajubd49** [comment]
Please enlighten me with some details. How did this crash happened, which version of XCode you are using and reproducible steps?

**Comment by MrVlad001** [comment]
the same issue,
Xcode 11.0

**Comment by rajubd49** [comment]
Please check the updated repo, resolved now.
